//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlbumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlbumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AlbumResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        internal static string AnimeSketchHeading {
            get {
                return ResourceManager.GetString("AnimeSketchHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime Sketch.
        /// </summary>
        internal static string AnimeSketchParagraph {
            get {
                return ResourceManager.GetString("AnimeSketchParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Gallery.
        /// </summary>
        internal static string BrowseGallery {
            get {
                return ResourceManager.GetString("BrowseGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funky Girl.
        /// </summary>
        internal static string FunkyGirlHeading {
            get {
                return ResourceManager.GetString("FunkyGirlHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funky Girl Sketch.
        /// </summary>
        internal static string FunkyGirlParagrapgh {
            get {
                return ResourceManager.GetString("FunkyGirlParagrapgh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrithikRoshan.
        /// </summary>
        internal static string HeadingHrithikRoshan {
            get {
                return ResourceManager.GetString("HeadingHrithikRoshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RanbirSingh.
        /// </summary>
        internal static string HeadingRanbirSingh {
            get {
                return ResourceManager.GetString("HeadingRanbirSingh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RobertDownyJr.
        /// </summary>
        internal static string HeadingRobertDownyJr {
            get {
                return ResourceManager.GetString("HeadingRobertDownyJr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luffy.
        /// </summary>
        internal static string LuffyHeading {
            get {
                return ResourceManager.GetString("LuffyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luffy Sketch.
        /// </summary>
        internal static string LuffySketchParagraph {
            get {
                return ResourceManager.GetString("LuffySketchParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
    }
}
